---
- name: "thunar | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: thunar_distribution_config

- name: "thunar | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: thunar_distribution_config.stat.exists


# - name: "thunar | Configure thunar"
#   ansible.builtin.copy:
#     src: thunar
#     dest: "{{ ansible_user_dir }}/.config/"
#     mode: "0644"
#     directory_mode: "0755"
#     force: true
