---
- name: "unclutter | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: unclutter_distribution_config

- name: "unclutter | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: unclutter_distribution_config.stat.exists


# - name: "unclutter | Configure unclutter"
#   ansible.builtin.copy:
#     src: unclutter
#     dest: "{{ ansible_user_dir }}/.config/"
#     mode: "0644"
#     directory_mode: "0755"
#     force: true
