---
- name: "mpv | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: mpv_distribution_config

- name: "mpv | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: mpv_distribution_config.stat.exists


# - name: "mpv | Configure mpv"
#   ansible.builtin.copy:
#     src: mpv
#     dest: "{{ ansible_user_dir }}/.config/"
#     mode: "0644"
#     directory_mode: "0755"
#     force: true
