---
- name: "feh | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: feh_distribution_config
  
- name: "feh | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: feh_distribution_config.stat.exists

# - name: "feh | Configure feh"
#   ansible.builtin.copy:
#     src: feh
#     dest: "{{ ansible_user_dir }}/.config/"
#     mode: "0644"
#     directory_mode: "0755"
#     force: true
