---
- name: "local | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: local_distribution_config

- name: "local | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: local_distribution_config.stat.exists

- name: "local | Ensure .local directory exists"
  ansible.builtin.file:
    path: "{{ item }}"
    mode: "0755"
    state: directory
  loop:
    - ~/.local

- name: "local | Configure local"
  ansible.builtin.copy:
    src: .local/
    dest: "{{ ansible_user_dir }}/.local/"
    mode: "0644"
    directory_mode: "0755"
    force: true
