---
- name: "xbacklight | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: xbacklight_distribution_config

- name: "xbacklight | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: xbacklight_distribution_config.stat.exists


# - name: "xbacklight | Configure xbacklight"
#   ansible.builtin.copy:
#     src: xbacklight
#     dest: "{{ ansible_user_dir }}/.config/"
#     mode: "0644"
#     directory_mode: "0755"
#     force: true
