---
- name: "xed | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: xed_distribution_config

- name: "xed | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: xed_distribution_config.stat.exists


- name: "xed | Configure xed"
  ansible.builtin.copy:
    src: xed
    dest: "{{ ansible_user_dir }}/"
    mode: "0644"
    directory_mode: "0755"
    force: true
