---
- name: "tumbler | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: tumbler_distribution_config

- name: "tumbler | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: tumbler_distribution_config.stat.exists


# - name: "tumbler | Configure tumbler"
#   ansible.builtin.copy:
#     src: tumbler
#     dest: "{{ ansible_user_dir }}/.config/"
#     mode: "0644"
#     directory_mode: "0755"
#     force: true
