---
- name: "i3 | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: i3_distribution_config

- name: "i3 | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: i3_distribution_config.stat.exists


- name: "i3 | Configure i3"
  ansible.builtin.copy:
    src: i3
    dest: "{{ ansible_user_dir }}/.config/"
    mode: "0644"
    directory_mode: "0755"
    force: true

# - name: "i3 | Change permissions on .config/i3/scripts/* files"
#   file:
#     path: "~/.config/i3/scripts/*"
#     state: file
#     owner: breez
#     group: breez
#     mode: +x

# - name: Check system information
#   shell: 
#   "lsb_release -a"
#   register: os_info
    
# - debug:
# msg: "{{os_info.stdout_lines}}"


- name: i3 | change permissions on .config/i3/scripts
  shell: "chmod +x ~/.config/i3/scripts/*"


