---
- name: "lxappearance | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: lxappearance_distribution_config

- name: "lxappearance | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: lxappearance_distribution_config.stat.exists


# - name: "lxappearance | Configure lxappearance"
#   ansible.builtin.copy:
#     src: lxappearance
#     dest: "{{ ansible_user_dir }}/.config/"
#     mode: "0644"
#     directory_mode: "0755"
#     force: true
