---
- name: "flameshot | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: flameshot_distribution_config

- name: "flameshot | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: flameshot_distribution_config.stat.exists

# - name: "flameshot | Configure flameshot"
#   ansible.builtin.copy:
#     src: flameshot
#     dest: "{{ ansible_user_dir }}/.config/"
#     mode: "0644"
#     directory_mode: "0755"
#     force: true
