---
- name: "alfa-network-adapter | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: alfa-network-adapter

- name: "alfa-network-adapter | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: alfa-network-adapter_distribution_config.stat.exists


# - name: "arandr | Configure arandr"
#   ansible.builtin.copy:
#     src: arandr
#     dest: "{{ ansible_user_dir }}/.config/"
#     mode: "0644"
#     directory_mode: "0755"
#     force: true
