---
- name: "betterlockscreen | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: betterlockscreen_distribution_config

- name: "betterlockscreen | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: betterlockscreen_distribution_config.stat.exists


# - name: "betterlockscreen | Configure betterlockscreen"
#   ansible.builtin.copy:
#     src: betterlockscreen
#     dest: "{{ ansible_user_dir }}/.config/"
#     mode: "0644"
#     directory_mode: "0755"
#     force: true
