---
- name: "nwg-look | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: nwg_look_distribution_config

- name: "nwg-look | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: nwg_look_distribution_config.stat.exists


- name: "nwg-look | Configure nwg-look"
  ansible.builtin.copy:
    src: nwg-look
    dest: "{{ ansible_user_dir }}/.config/"
    mode: "0644"
    directory_mode: "0755"
    force: true
