---
- name: "xsettingsd | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: xsettingsd_distribution_config

- name: "xsettingsd | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: xsettingsd_distribution_config.stat.exists


- name: "xsettingsd | Configure xsettingsd"
  ansible.builtin.copy:
    src: xsettingsd
    dest: "{{ ansible_user_dir }}/.config/"
    mode: "0644"
    directory_mode: "0755"
    force: true
