---
- name: "imagemagick | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: imagemagick_distribution_config

- name: "imagemagick | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: imagemagick_distribution_config.stat.exists


# - name: "imagemagick | Configure imagemagick"
#   ansible.builtin.copy:
#     src: imagemagick
#     dest: "{{ ansible_user_dir }}/.config/"
#     mode: "0644"
#     directory_mode: "0755"
#     force: true
