---
- name: "lightdm | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: lightdm_distribution_config

- name: "lightdm | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: lightdm_distribution_config.stat.exists

# - name: "lightdm | Configure lightdm"
#   ansible.builtin.copy:
#     src: lightdm
#     dest: "{{ ansible_user_dir }}/.config/"
#     mode: "0644"
#     directory_mode: "0755"
#     force: true
