---
- name: "thunar-plugins | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: thunar_plugins_distribution_config

- name: "thunar-plugins | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: thunar_plugins_distribution_config.stat.exists


# - name: "thunar-plugins | Configure thunar-archive-plugin"
#   ansible.builtin.copy:
#     src: thunar-plugins
#     dest: "{{ ansible_user_dir }}/.config/"
#     mode: "0644"
#     directory_mode: "0755"
#     force: true

# - name: "thunar-plugins | Configure thunar-volman"
#   ansible.builtin.copy:
#     src: thunar-plugins
#     dest: "{{ ansible_user_dir }}/.config/"
#     mode: "0644"
#     directory_mode: "0755"
#     force: true
