---
- name: "wallpaper | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: wallpaper_distribution_config

- name: "wallpaper | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: wallpaper_distribution_config.stat.exists

- name: "wallpaper | Copy wallpaper"
  ansible.builtin.copy:
    src: wallpaper
    dest: "{{ ansible_user_dir }}/.config/"
    mode: "0644"
    directory_mode: "0755"
    force: true

- name: "wallpaper | {{ ansible_distribution }} | copy .fehbg"
  ansible.builtin.copy:
    src: .fehbg
    dest: "{{ ansible_user_dir }}/"
    mode: "0644"
    directory_mode: "0755"
    force: true