---
- name: "playerctl | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: playerctl_distribution_config

- name: "playerctl | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: playerctl_distribution_config.stat.exists


# - name: "playerctl | Configure playerctl"
#   ansible.builtin.copy:
#     src: playerctl
#     dest: "{{ ansible_user_dir }}/.config/"
#     mode: "0644"
#     directory_mode: "0755"
#     force: true
